# Generated by Django 5.2.17 on 2026-08-19 10:33

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, help_text='Full name, used in the header, footer, and SEO metadata.', max_length=100)),
                ('professional_title', models.CharField(blank=True, help_text='e.g. "Software Engineer & Architect".', max_length=150)),
                ('tagline', models.CharField(blank=True, help_text='Short specialization line (e.g. Microsoft/.NET focus).', max_length=255)),
                ('contact_email', models.EmailField(blank=True, help_text='Fallback contact address (obfuscated when rendered).', max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('resume_document', models.ForeignKey(blank=True, help_text='Downloadable resume (re-upload in admin to update it).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='e.g. Mastodon, Stack Overflow.', max_length=100)),
                ('url', models.URLField()),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_profiles', to='core.sitesettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
