# Generated by Django 5.2.17 on 2026-08-19 10:53

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Override the canonical URL. Defaults to this page's own URL.")),
                ('date', models.DateField(help_text='Publication date (ordering and display).')),
                ('summary', models.TextField(help_text='List summary and default meta description.')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('code', 6), ('image', 10), ('quote', 12)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Heading text.', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3')], 'help_text': 'Semantic heading level (keep the document outline logical).'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'document-link'], 'template': 'core/blocks/paragraph_block.html'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Language label shown above the code (e.g. csharp).', 'max_length': 50, 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Raw code; rendered verbatim.', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('language', 4), ('code', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alternative text describing the image (accessibility).', 'max_length': 255, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 7), ('alt_text', 8), ('caption', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {'required': True}), 12: ('wagtail.blocks.StructBlock', [[('quote', 11), ('attribution', 9)]], {})}, help_text='Article content.')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Header image and social card.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('social_image', models.ForeignKey(blank=True, help_text='Image used for social/link previews (Open Graph, Twitter).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.articlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.ArticleTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Override the canonical URL. Defaults to this page's own URL.")),
                ('intro', models.TextField(blank=True, help_text='Optional lead-in for the article list.')),
                ('social_image', models.ForeignKey(blank=True, help_text='Image used for social/link previews (Open Graph, Twitter).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
