# Generated by Django 5.2.17 on 2026-08-19 10:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Override the canonical URL. Defaults to this page's own URL.")),
                ('hero_heading', models.CharField(help_text='Owner name + title, shown above the fold (FR-005).', max_length=150)),
                ('hero_subheading', models.CharField(help_text='Specialization statement (e.g. Microsoft/.NET focus).', max_length=255)),
                ('primary_cta_label', models.CharField(default='Get in touch', help_text='Call-to-action label, e.g. "Get in touch" (FR-006).', max_length=60)),
                ('intro', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('code', 6), ('image', 10), ('quote', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Heading text.', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3')], 'help_text': 'Semantic heading level (keep the document outline logical).'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'document-link'], 'template': 'core/blocks/paragraph_block.html'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Language label shown above the code (e.g. csharp).', 'max_length': 50, 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Raw code; rendered verbatim.', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('language', 4), ('code', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alternative text describing the image (accessibility).', 'max_length': 255, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 7), ('alt_text', 8), ('caption', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {'required': True}), 12: ('wagtail.blocks.StructBlock', [[('quote', 11), ('attribution', 9)]], {})}, help_text='Optional short value proposition below the hero.')),
                ('primary_cta_page', models.ForeignKey(help_text='Target of the primary CTA (typically the contact page).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.page')),
                ('social_image', models.ForeignKey(blank=True, help_text='Image used for social/link previews (Open Graph, Twitter).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_projects', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_articles', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
